import com.rolea.learning.validation.domain.Product;
import com.rolea.learning.validation.service.ValidationError;
import com.rolea.learning.validation.service.ValidationResultContainer;
import com.rolea.learning.validation.service.ProductAdditionalData;

global ValidationResultContainer resultContainer;
global ProductAdditionalData additionalData;

rule "Product name is not null"
    salience 20
    when
        productInstance:Product(name == null);
    then
        String message = String.format("Product with id %d has a null name", productInstance.getId());
        resultContainer.addValidationError(productInstance, message);
end