import com.rolea.learning.validation.domain.Product;
import com.rolea.learning.validation.service.ValidationError;
import com.rolea.learning.validation.service.ValidationResultContainer;
import com.rolea.learning.validation.service.ProductAdditionalData;

global ValidationResultContainer resultContainer;
global ProductAdditionalData additionalData;

rule "Product price is non-null and positive"
    salience 10
    when
        productInstance:Product(price == null || price < 0);
    then
        String message = String.format("Product with id %d has a null or negative price", productInstance.getId());
        resultContainer.addValidationError(productInstance, message);
end