import com.rolea.learning.validation.domain.Product;
import com.rolea.learning.validation.service.ValidationError;

global com.rolea.learning.validation.service.ValidationResult validationResult;
global com.rolea.learning.validation.service.ProductAdditionalData additionalData;

dialect  "mvel"
dialect  "java"

rule "Ensure product has a positive price"
    when
        productInstance:Product(price == null || price < 0);
    then
        String message = String.format("Product with id %d has a null or negative price", productInstance.getId());
        validationResult.addValidationError(ValidationError.builder().message(message).build());
end