import com.rolea.learning.validation.domain.Product;
import com.rolea.learning.validation.service.ValidationError;
import com.rolea.learning.validation.service.ValidationResultContainer;
import com.rolea.learning.validation.service.ProductAdditionalData;

global ValidationResultContainer resultContainer;
global ProductAdditionalData additionalData;

salience 10;

rule "Product has at least one category"
    when
        productInstance:Product(categories == null || categories.isEmpty);
    then
        String message = String.format("Product with id %d has no categories", productInstance.getId());
        resultContainer.addValidationError(productInstance, message);
end