import com.rolea.learning.validation.domain.Product;
import com.rolea.learning.validation.service.ValidationWarning;
import com.rolea.learning.validation.service.ProductAdditionalData;
import java.util.*;

global com.rolea.learning.validation.service.ValidationResult validationResult;
global com.rolea.learning.validation.service.ProductAdditionalData additionalData;

dialect  "mvel"
dialect  "java"

function boolean validateStock(Product product, ProductAdditionalData additionalData) {
    Map<Long, Long> stockInfo = additionalData.getProductStockData();

    return !(stockInfo.containsKey(product.getId()) &&
             stockInfo.get(product.getId()) != null &&
             stockInfo.get(product.getId()) > 0);
}

rule "Ensure there is a positive stock for a product"
    when
        productInstance:Product()
        eval(validateStock(productInstance, additionalData))
    then
        String message = String.format("Product with id %d is currently out of stock", productInstance.getId());
        validationResult.addValidationWarning(ValidationWarning.builder().message(message).build());
end